- job:
    name: openshift-test
    parent: base-openshift
    run: test.yaml
    vars:
      base_image: "python:3.6"

- project:
    check:
      jobs:
        - openshift-test
    gate:
      jobs:
        - openshift-test
